### ISSUE TITLE
Supporting stories

### ISSUE THREAD

**Issue by xplosionmind** [VernissageApp/Vernissage#39] opened 2023-04-18 07:48 UTC
This app is way better than the official one, and it lacking support for stories constitutes the greatest limit for me!

**Comment by BarterClub** [comment] 2023-07-02 23:27
Yes please

**Comment by fishcharlie** [comment] 2024-04-28 16:26
@mczachurski Why is this marked as working as intended?

**Comment by mczachurski** [comment] 2024-07-29 14:25
The application was designed with the primary focus on displaying photos. Other media types, such as videos, stories, and similar content, were not a priority during the development process.

**Closed by mczachurski** 2024-07-29 14:25 UTC
Labels: enhancement, works as intended

**Comment by fishcharlie** [comment] 2024-07-29 15:38
@mczachurski Would you accept PR(s) to implement those features or not?
